name: 'Cargo Static Build Action'
description: 'Build static binaries for rust app, using MUSL'
branding:
  icon: package
  color: black
inputs:
  cmd:
    description: 'build command'
    required: true
    default: 'cargo build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.cmd }}
